# api-rest-laravel

###
# group: user
# @name register
POST {{host}}/api/user/register
Content-Type: application/x-www-form-urlencoded
Cookie: XDEBUG_SESSION=PHPSTORM; curso_laravel_session=eyJpdiI6IjFJM0Z3M29wa0J6bWpuSWIwQmNZZUE9PSIsInZhbHVlIjoiVlI1d1JhZkNOVWJJSm5McENncVE3R0lCYWJiRDB3MkpTYzRkSW9iTlc3bndLemI4RDBaU3FVeHdka1VQOWtTU1Buc0xPajFGSXpiaC9OaE1MMktlMXUwQkNsU282czdxbzJpYzNLY1RJSzJpSll0SFd3NEJ5dmR2OW5YRzZLZVoiLCJtYWMiOiIxN2QyMDAwMWVmMzAwNjM4Mzc1NGQyMzZmNDZkYjEwYmI0YjgyOTRhNjE2YmU1YmU4MWQzNWIwYjJhNzU4MmZiIiwidGFnIjoiIn0%3D


json = {"name": "Pedro","surname": "LLongo","email": "pedrollongo1279@gmail.com","password" : "pedro"}

###
# group: user
# @name login
POST {{host}}/api/user/login
Content-Type: application/x-www-form-urlencoded

json = {"email": "pedrollongo1279@gmail.com","password" : "pedro", "getToken": "false"}
> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Headers option exists", function () {
        client.assert(response.body.hasOwnProperty("headers"), "Cannot find 'headers' option in response");
    });

    client.test("Response content-type is json", function () {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
    //Saving a cookie from the first Set-Cookie header
    client.global.set("my_cookie", response.headers.valuesOf("Set-Cookie")[0]);
%}

###
# group: user
# @name update

PUT {{host}}/api/user/update
Content-Type: application/x-www-form-urlencoded
Authorization: {{token}}


json = {"name": "Gonso","surname": "Fraguel","email": "pedrollongo1279@gmail.com"}


###
# group: user
# @name getimage
GET {{host}}/api/user/avatar/1559723020cog.jpg
Content-Type: application/x-www-form-urlencoded

json = {"name": "Pedro","surname": "LLongo","email": "pedrollongo@gmail.com","password" : "pedro"}

###
# group: user
# @name detail
GET {{host}}/api/user/detail/4
Content-Type: application/x-www-form-urlencoded

json = {"name": "Pedro","surname": "LLongo","email": "pedrollongo@gmail.com","password" : "pedro"}

###
# group: user
# @name upload
POST {{host}}/api/user/upload
Content-Type: application/x-www-form-urlencoded
Authorization: ""
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name = "file0"; filename="cog.png"

< /Users/pedro/PhpstormProjects/decobelda/htpdocs/wp-content/themes/deco/framework/images/icons/cog.png
--WebAppBoundary

###
# group: user
# @name upload Copy
POST {{host}}/api/register
Content-Type: application/x-www-form-urlencoded

json = {"name": "Pedro","surname": "LLongo","email": "pedrollongo@gmail.com","password" : "pedro"}

###
# group: user
# @name update
PUT {{host}}/api/user/update
Content-Type: application/x-www-form-urlencoded
Authorization: {{token}}

json = {"name": "juan5","juan5": "LLongo","email": "juan@juan.com","password" : "juan112"}

###
# group: category
# @name update Copy
PUT {{host}}/api/user/update
Content-Type: application/x-www-form-urlencoded
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjQsImVtYWlsIjoicGVkcm9sbG9uZ29AZ21haWwuY29tIiwibmFtZSI6IlBlZHJvIiwic3VybmFtZSI6IkxMb25nbyIsImlhdCI6MTU1OTQ5OTk2NSwiZXhwIjoxNTYwMTA0NzY1fQ.Az9_vNePN-5Tnr3YkctNIjKJhG1hIUj0AXnSkw98yag

json = {"name": "Pedro","surname": "LLongo","email": "pedrollongo@gmail.com","password" : "pedro"} &
Authorization = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjQsImVtYWlsIjoicGVkcm9sbG9uZ29AZ21haWwuY29tIiwibmFtZSI6IlBlZHJvIiwic3VybmFtZSI6IkxMb25nbyIsImlhdCI6MTU1OTQ5OTk2NSwiZXhwIjoxNTYwMTA0NzY1fQ.Az9_vNePN-5Tnr3YkctNIjKJhG1hIUj0AXnSkw98yag

###
# group: category
# @name category index
GET {{host}}/api/category
Content-Type: application/x-www-form-urlencoded

json = ''

###
# group: category
# @name category store
POST {{host}}/api/category
Content-Type: application/x-www-form-urlencoded
Authorization: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjMwLCJlbWFpbCI6InBlZHJvbGxvbmdvMTI3OUBnbWFpbC5jb20iLCJuYW1lIjoiR29uc28iLCJzdXJuYW1lIjoiRnJhZ3VlbCIsImlhdCI6MTcxMjU3MTYzNSwiZXhwIjoxNzEzMTc2NDM1fQ.mt77B8e6sY94jZOd7FJNyDTuAgVn9qZcSmJwdN2a1HY"

json = {"name": "nueva categoria"}

###
# group: category
# @name category show
GET {{host}}/api/category/1
Content-Type: application/x-www-form-urlencoded

###
# group: posts
# @name upload Copy
POST {{host}}/api/user/upload?
    A=
    Content-Type: application/x-www-form-urlencoded
Authorization: {{token}}
#Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name = "file0"; filename="cog.pxm"

< /Users/pedro/Desktop/cog.pxm
--WebAppBoundary

###
# group: posts
# @name post index
GET {{host}}/api/post
Content-Type: application/x-www-form-urlencoded

###
# group: posts
# @name post store
POST {{host}}/api/post
Content-Type: application/x-www-form-urlencoded
Authorization: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjQsImVtYWlsIjoicGVkcm9sbG9uZ29AZ21haWwuY29tIiwibmFtZSI6IlBlZHJvMiIsInN1cm5hbWUiOiJMTG9uZ28yIiwiaWF0IjoxNTU5NzU3Mzg5LCJleHAiOjE1NjAzNjIxODl9.-EYe5RmNTzgTP1T913r7FrqEVbifN7Wu4w9g1zfAaJw"

json = {
        "category_id": 1,
        "title": "nuevo post",
        "content": "contenido nuevo post",
        "image": "1559723020cog.jpg"
}

###
# group: posts
# @name post show
GET {{host}}/api/post/1
Content-Type: application/x-www-form-urlencoded

###
# group: posts
# @name post update
PUT {{host}}/api/post/1
=
Content-Type: application/x-www-form-urlencoded
Authorization: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjQsImVtYWlsIjoicGVkcm9sbG9uZ29AZ21haWwuY29tIiwibmFtZSI6IlBlZHJvMiIsInN1cm5hbWUiOiJMTG9uZ28yIiwiaWF0IjoxNTU5NzU3Mzg5LCJleHAiOjE1NjAzNjIxODl9.-EYe5RmNTzgTP1T913r7FrqEVbifN7Wu4w9g1zfAaJw"

json = {
        "category_id": 1,
        "title": "Actulizado post",
        "content": "contenido Actulizado post",
        "image": "1559723020cog.jpg"
}

###
# group: posts
# @name post delete
DELETE {{host}}/api/post/1
Content-Type: application/x-www-form-urlencoded
Authorization: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjQsImVtYWlsIjoicGVkcm9sbG9uZ29AZ21haWwuY29tIiwibmFtZSI6IlBlZHJvMiIsInN1cm5hbWUiOiJMTG9uZ28yIiwiaWF0IjoxNTU5NzU3Mzg5LCJleHAiOjE1NjAzNjIxODl9.-EYe5RmNTzgTP1T913r7FrqEVbifN7Wu4w9g1zfAaJw"

json = {
        "category_id": 1,
        "title": "Actulizado post",
        "content": "contenido Actulizado post",
        "image": "1559723020cog.jpg"
}

###
# group: posts
# @name getimage
GET {{host}}/api/post/image/1560010472cog.jpg
Content-Type: application/x-www-form-urlencoded

json = {"name": "Pedro","surname": "LLongo","email": "pedrollongo@gmail.com","password" : "pedro"}

###
# group: posts
# @name get posts by user
GET {{host}}/api/post/user/1
Content-Type: application/x-www-form-urlencoded

json = {"name": "Pedro","surname": "LLongo","email": "pedrollongo@gmail.com","password" : "pedro"}

###
# group: posts
# @name get posts by category
GET {{host}}/api/post/category/1
Content-Type: application/x-www-form-urlencoded

json = {"name": "Pedro","surname": "LLongo","email": "pedrollongo@gmail.com","password" : "pedro"}
